version: '3'
services:
  backend:
    build:
      context: . # Context is the current directory
      dockerfile: ./Dockerfile # Dockerfile is in the current directory
    volumes:
      - .:/app # Mount the current directory to /app in the container
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: air
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
  
