version: '3'
services:
  backend:
    build: .
    volumes:
      - .:/app # Mount the current directory to /app in the container
    working_dir: /app
    command: air
    ports:
      - "8080:8080"
  
